<a href="https://colab.research.google.com/github/coma-nrdhs/semester-2/blob/main/array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import numpy as np

In [28]:
my_array = np.array([9,8,7,10,11])

In [15]:
type(my_array)

numpy.ndarray

In [29]:
my_array.shape

(5,)

In [17]:
my_array.ndim

1

In [18]:
my_array.dtype

dtype('int64')

In [19]:
print(len(my_array))

6


In [20]:
i = 0
while i < 5 :
  print(my_array[i])
  i = i+1

9
8
7
10
11


In [24]:
i = 0
while i < 5 :
  if my_array[i] == 4 :
    print(i)
    break
  i = i + 1
if i == 5:
  print(-1)


-1


In [51]:
my_array2 = np.zeros(6)
i = 0
while i < 5 :
  my_array2[i] = int(input("enter number: "))
  i = i + 1
print(my_array2)

enter number: 11
enter number: 10
enter number: 9
enter number: 8
enter number: 7
[11. 10.  9.  8.  7.  0.]


In [52]:

i = 5
while i > 3:
  my_array2[i] = my_array2[i-1]
  i = i -1
print(my_array2)
my_array2[3] = 25
print(my_array2)

[11. 10.  9.  8.  8.  7.]
[11. 10.  9. 25.  8.  7.]
